### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by agarstang** [crayfishx/lookup_http#2]
Issue at [line](https://github.com/crayfishx/jerakia/blob/master/lib/jerakia/datasource/http.rb#L59).

`undefined method `[]' for nil:NilClass (NoMethodError)`

When my datasource returns blank data or a 404 the `data` variable does not contain parsed output that can be access via `[]`.

**Comment by crayfishx** [comment]
Hi @agarstang  - you raised this against the lookup_http project but your code is from Jerakia :)  - I think this is more to do with how Jerakia parses the response from lookup_http therefore I've attempted to put a fix in there.

Can you review https://github.com/crayfishx/jerakia/issues/59 and see if that implements the correct behaviour?

**Comment by agarstang** [comment]
@crayfish whoops! I blame Fridays!

**Comment by crayfishx** [comment]
@agarstang hehe no worries, does the jerakia PR sort your issue out?
